from os import getenv


DEV = getenv("FLASK_ENV") != "production"

# MongoDB Local
LOCAL_CONNECTION_STRING = getenv("LOCAL_CONNECTION_STRING")
LOCAL_DB_NAME = getenv("LOCAL_DB_NAME")
# Redis Local
LOCAL_REDIS_USER = getenv("LOCAL_REDIS_USER")
LOCAL_REDIS_PASSWORD = getenv("LOCAL_REDIS_PASSWORD")
LOCAL_REDIS_HOST = getenv("LOCAL_REDIS_HOST")
LOCAL_REDIS_PORT = getenv("LOCAL_REDIS_PORT")


''' Configurações do banco de dados e coleções antigo gmonitor '''

'''DATABASE'''

CONST_MONGO_URL = getenv('CONST_MONGO_URL')
CONST_DATABASE = getenv('CONST_DATABASE')
CONST_BI_DATABASE = getenv('BI_DATABASE')
CONST_REDIS_HOST = getenv('CONST_REDIS_HOST')
CONST_REDIS_PORT =  int(getenv('CONST_REDIS_PORT'))
CONST_REDIS_PASSWORD = getenv('CONST_REDIS_PASSWORD')

'''COLLECTIONS'''
CONST_ABASTECIMENTOS_COLLECTION = getenv('CONST_ABASTECIMENTOS_COLLECTION')
CONST_TM_TANQUES_COLLECTION = getenv('CONST_TM_TANQUES_COLLECTION')
CONST_VENDEDORES_COLLECTION = getenv('CONST_VENDEDORES_COLLECTION')
CONST_ADMINISTRATOR_COLLECTION = getenv('CONST_ADMIN_COLLECTION')
CONST_USER_PROFILE_COLLECTION = getenv('CONST_USER_PROFILE_COLLECTION')
CONST_CONSOLIDATE_COLLECTION = getenv('CONST_CONSOLIDATE_COLLECTION')
CONST_PUSH_NOTIFICATION_COLLECTION = getenv('CONST_PUSH_NOTIFICATION_COLLECTION')
CONST_NOTIFICATION_COLLECTION = getenv('CONST_NOTIFICATION_COLLECTION')
CONST_AFERICAO_COLLECTION = "Afericoes"
CONST_LOGS_COLLECTION = "AppLog_Usuarios_Login"
CONST_TM_BICOS_COLLECTION = "TmBicos"
CONST_CONSOLIDATE_FUELS_COLLECTION = "VendaDiariaCombConsolidada"
CONST_SIGLAS_COMBUSTIVEIS_COLLECTION = "SiglasCombustiveis"
CONST_BI_COMBUSTIVEIS_COLLECTION = "Combustivel"


'''Caches'''
CACHE_MEMBERS_MAX_SIZE = 200
CONST_CACHE_EXPIRATION = 60 * 60 * 8 # 8 hours

'''GENERAL'''
TOKEN_SECRET = getenv('TOKEN_SECRET')
GENERAL_HASH_KEY = getenv('GENERAL_HASH_KEY')
AUTH_URL = getenv('AUTH_URL')
FIREBASE_CRENDENTIALS = getenv('FIREBASE_CRENDENTIALS')
WORKERS = bool(getenv('WORKERS'))
BIG_QUERY_CRENDENTIALS = "src/middleware/striking-decker-420402-617b2da240ba.json"


'''PASSWORD FOR NOTIFICATION AUTH'''
NOTIFICATION_AUTH_PASSWORD = getenv('NOTIFICATION_AUTH_PASSWORD')
NOTIFICATION_AUTH_USERNAME = getenv('NOTIFICATION_AUTH_USERNAME')


'''JWT_SECRET'''
JWT_SECRET = getenv('JWT_SECRET')


'''ACESSO AO SERVIÇO DE IA'''
GASMONITOR_AI_SERVICE_KEY = getenv("GASMONITOR_AI_SERVICE_KEY")
GASMONITOR_AI_SERVICE_URL = getenv("GASMONITOR_AI_SERVICE_URL")

'''PRIMEIRA QUESTAO AO AGENTE DE IA'''
AI_AGENT_INITIAL_QUESTION = "#user_info"
